React-Redux Capstone PR
adamteddychang/stocks-app pull request #1
Opened 2021-12-23 19:24 UTC by adamteddychang

2021-12-23 21:00 UTC, mikenath223 requested changes
Hi there, 

Awesome job on making the changes requested by the previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet. Let's work on those.


 ## Required Changes ♻️
_Kindly check the comments under the review._


Happy coding, Cheers!🚀🚀

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, whether it's valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-23 21:03 UTC, mikenath223 commented on .eslintrc.json
> +    "react/prop-types": "off"
- [ ] Kindly ensure the rules here match the given [linting rules](https://github.com/microverseinc/linters-config/blob/master/react-redux/.eslintrc.json).

2021-12-23 21:03 UTC, mikenath223 commented on README.md
> +![Capture2](https://user-images.githubusercontent.com/63560332/147289716-2f677568-42b1-4925-876f-0cb03b145f52.PNG)
- [ ] You failed to speak about a piece of code you find interesting. Please record an additional loom video talking about this.

2021-12-23 21:41 UTC, adamteddychang commented on README.md
> +![Capture2](https://user-images.githubusercontent.com/63560332/147289716-2f677568-42b1-4925-876f-0cb03b145f52.PNG)
Here is the short video for the piece of code I found interesting: 
[Interesting Code Video](https://www.loom.com/share/5b7e7f1321ec444fb6a59a098eedb804)

2021-12-24 00:45 UTC, ArthurGC approved these changes
# Approved project!  💯 ✅ 🥳 🎈 🎉
Hi  @adamteddychang 

Amazing job implementing suggestions from the previous reviewer! 💯 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![](https://media1.giphy.com/media/3o7buh8WbaZLupolXi/giphy.gif)


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2021-12-24 07:06 UTC, merged